# Generated by Django 3.1.7 on 2021-03-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('organism', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Seq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instrument', models.CharField(choices=[('Illumina HiSeq', 'Illumina HiSeq'), ('NextSeq 500', 'NextSeq 500'), ('Illumina MiSeq', 'Illumina MiSeq'), ('GridION', 'GridION'), ('MinION', 'MinION')], max_length=100)),
                ('strategy', models.CharField(choices=[('WGA', 'WGA'), ('WGS', 'WGS')], max_length=100)),
                ('source', models.CharField(choices=[('genomics', 'genomics'), ('metagenomics', 'metagenomics')], max_length=100)),
                ('layout', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('seqfile', models.FileField(blank=True, null=True, upload_to='seqs/')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seqs', to='project.sample')),
            ],
        ),
    ]
